# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vegaload < Formula
  desc "Open-source load testing for code and AI agents. One static binary."
  homepage "https://github.com/vegaload/vegaload"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vegaload/vegaload/releases/download/v0.1.0/vegaload_0.1.0_darwin_amd64.tar.gz"
      sha256 "b7d1ba55efdf7c33234fbaefbe35e9f8c178cb41bfb298415904ba044c8224f1"

      define_method(:install) do
        bin.install "vegaload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vegaload/vegaload/releases/download/v0.1.0/vegaload_0.1.0_darwin_arm64.tar.gz"
      sha256 "caf16fe20b14572f077226387188fa902a3904e6374568c2d07251e94b3cb88d"

      define_method(:install) do
        bin.install "vegaload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegaload/vegaload/releases/download/v0.1.0/vegaload_0.1.0_linux_amd64.tar.gz"
      sha256 "38397522c65ab8295a77068a7c3b402b43d8e8fe0e2f3a665e6bc1f44c12c6cf"
      define_method(:install) do
        bin.install "vegaload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegaload/vegaload/releases/download/v0.1.0/vegaload_0.1.0_linux_arm64.tar.gz"
      sha256 "76a1ecfd59c91fb9db93fdb79e772eda0590eb7dee086ee8a55c3c2a431357ec"
      define_method(:install) do
        bin.install "vegaload"
      end
    end
  end

  test do
    assert_match "vegaload #{version}", shell_output("#{bin}/vegaload version")
  end
end
