# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vegaload < Formula
  desc "Open-source load testing for code and AI agents. One static binary."
  homepage "https://github.com/vegaload/vegaload"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vegaload/vegaload/releases/download/v0.6.0/vegaload_0.6.0_darwin_amd64.tar.gz"
      sha256 "2093a887bfd0b336cf1ec15707e73630bd54d920684b662a374398a7037ea15d"

      define_method(:install) do
        bin.install "vegaload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vegaload/vegaload/releases/download/v0.6.0/vegaload_0.6.0_darwin_arm64.tar.gz"
      sha256 "f6e70eed3d7676040167a4ae3b8d0e466d334c48e5f584ce02941b830d59c40e"

      define_method(:install) do
        bin.install "vegaload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegaload/vegaload/releases/download/v0.6.0/vegaload_0.6.0_linux_amd64.tar.gz"
      sha256 "fc1de2d34b438c3d3e7b63996343690c881f5053ef9ea62c9abb67ae908edbe7"
      define_method(:install) do
        bin.install "vegaload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegaload/vegaload/releases/download/v0.6.0/vegaload_0.6.0_linux_arm64.tar.gz"
      sha256 "2db5af65ee6ce9b7e2c35f1e62832532eb7d9a4964e18d9611230d97325a78d5"
      define_method(:install) do
        bin.install "vegaload"
      end
    end
  end

  test do
    assert_match "vegaload #{version}", shell_output("#{bin}/vegaload version")
  end
end
