# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vegaload < Formula
  desc "Open-source load testing for code and AI agents. One static binary."
  homepage "https://github.com/vegaload/vegaload"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vegaload/vegaload/releases/download/v0.3.0/vegaload_0.3.0_darwin_amd64.tar.gz"
      sha256 "07edba73945b0eaa36259a14febf78befa972419e65e812030406b13183ac897"

      define_method(:install) do
        bin.install "vegaload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vegaload/vegaload/releases/download/v0.3.0/vegaload_0.3.0_darwin_arm64.tar.gz"
      sha256 "0c54b36c41790fe1856b3b31aa5c95e8e638c17d720a3fa3e7d212880c91472f"

      define_method(:install) do
        bin.install "vegaload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegaload/vegaload/releases/download/v0.3.0/vegaload_0.3.0_linux_amd64.tar.gz"
      sha256 "9a09b4fa2e68dc9fd07574d17cc602eb029ec9638bb43d9e6dc810d336e2a001"
      define_method(:install) do
        bin.install "vegaload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegaload/vegaload/releases/download/v0.3.0/vegaload_0.3.0_linux_arm64.tar.gz"
      sha256 "43cca3ad97e7fc3f0be26f7c4b0f4d20f7160a144b0ae2630f06d74f6db9f2e8"
      define_method(:install) do
        bin.install "vegaload"
      end
    end
  end

  test do
    assert_match "vegaload #{version}", shell_output("#{bin}/vegaload version")
  end
end
